### PR TITLE
Feat/bump dependencies

### PR DESCRIPTION
**Pull request by linuxbandit**
merging all dependabots at once (dependabot->branch and branch->master)

### CODE REVIEW

**Comment by linuxbandit** [comment]
I merged without approval because I like hurting myself and I really wanted to see if this would cause a mess

**Comment by linuxbandit** [comment]
@serge1peshcoff do you know why semantic-release-bot is not doing anything?

**Comment by WikiRik** [comment]
Maybe because the format is wrong? Normally we do feat(x): y

**Pull request merged**
